version: "3.8"
services:
  app:
    build: .
    volumes: 
      - .:/carshare
    ports:
      - 8000:8000
    image: app:carshare
    container_name: carshare_container
    command: python ./car_sharing/manage.py runserver 0.0.0.0:8000

     
