version: '3.9'

services:
  
  carshare:
    image: carshare
    build: .
    restart: always
    command : python ./car_sharing/manage.py runserver  0.0.0.0:8000
    ports:
      - "8000:8000"
